let express = require("express");
let app = express();
app.use(express.json());
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Methods",
    "GET, POST, OPTIONS, PUT, PATCH, DELETE, HEAD"
  );
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});
const theater = [
  {
    theater_name: "ABC Cinemas",
    timings: ["10:00 AM", "1:00 PM"],
  },
];

let seats1 = [
  {
    time: "10:00 AM",
    A: [
      { name: "A1", value: 1, price: 420 },
      { name: "A2", value: 0, price: 420 },
      { name: "A3", value: 0, price: 420 },
      { name: "A4", value: 0, price: 420 },
      { name: "A5", value: 1, price: 420 },
      { name: "A6", value: 0, price: 420 },
      { name: "A7", value: 1, price: 420 },
      { name: "A8", value: 0, price: 420 },
      { name: "A9", value: 0, price: 420 },
      { name: "A10", value: 1, price: 420 },
      { name: "A11", value: 0, price: 420 },
      { name: "A12", value: 0, price: 420 },
      { name: "A13", value: 0, price: 420 },
      { name: "A14", value: 0, price: 420 },
      { name: "A15", value: 0, price: 420 },
    ],
    B: [
      { name: "B1", value: 0, price: 420 },
      { name: "B2", value: 0, price: 420 },
      { name: "B3", value: 0, price: 420 },
      { name: "B4", value: 0, price: 420 },
      { name: "B5", value: 0, price: 420 },
      { name: "B6", value: 0, price: 420 },
      { name: "B7", value: 0, price: 420 },
      { name: "B8", value: 0, price: 420 },
      { name: "B9", value: 0, price: 420 },
      { name: "B10", value: 0, price: 420 },
      { name: "B11", value: 0, price: 420 },
      { name: "B12", value: 0, price: 420 },
      { name: "B13", value: 0, price: 420 },
      { name: "B14", value: 0, price: 420 },
      { name: "B15", value: 0, price: 420 },
    ],
    C: [
      { name: "C1", value: 0, price: 250 },
      { name: "C2", value: 0, price: 250 },
      { name: "C3", value: 0, price: 250 },
      { name: "C4", value: 0, price: 250 },
      { name: "C5", value: 1, price: 250 },
      { name: "C6", value: 0, price: 250 },
      { name: "C7", value: 0, price: 250 },
      { name: "C8", value: 0, price: 250 },
      { name: "C9", value: 0, price: 250 },
      { name: "C10", value: 0, price: 250 },
      { name: "C11", value: 0, price: 250 },
      { name: "C12", value: 0, price: 250 },
      { name: "C13", value: 0, price: 250 },
      { name: "C14", value: 0, price: 250 },
      { name: "C15", value: 0, price: 250 },
      { name: "C16", value: 0, price: 250 },
      { name: "C17", value: 0, price: 250 },
      { name: "C18", value: 0, price: 250 },
      { name: "C19", value: 0, price: 250 },
      { name: "C20", value: 0, price: 250 },
      { name: "C21", value: 0, price: 250 },
      { name: "C22", value: 0, price: 250 },
      { name: "C23", value: 0, price: 250 },
      { name: "C24", value: 0, price: 250 },
    ],
    D: [
      { name: "D1", value: 0, price: 250 },
      { name: "D2", value: 0, price: 250 },
      { name: "D3", value: 0, price: 250 },
      { name: "D4", value: 0, price: 250 },
      { name: "D5", value: 0, price: 250 },
      { name: "D6", value: 0, price: 250 },
      { name: "D7", value: 0, price: 250 },
      { name: "D8", value: 0, price: 250 },
      { name: "D9", value: 0, price: 250 },
      { name: "D10", value: 0, price: 250 },
      { name: "D11", value: 1, price: 250 },
      { name: "D12", value: 0, price: 250 },
      { name: "D13", value: 0, price: 250 },
      { name: "D14", value: 0, price: 250 },
      { name: "D15", value: 0, price: 250 },
      { name: "D16", value: 0, price: 250 },
      { name: "D17", value: 0, price: 250 },
      { name: "D18", value: 0, price: 250 },
      { name: "D19", value: 0, price: 250 },
      { name: "D20", value: 0, price: 250 },
      { name: "D21", value: 0, price: 250 },
      { name: "D22", value: 0, price: 250 },
      { name: "D23", value: 0, price: 250 },
      { name: "D24", value: 0, price: 250 },
    ],
    E: [
      { name: "E1", value: 0, price: 250 },
      { name: "E2", value: 0, price: 250 },
      { name: "E3", value: 0, price: 250 },
      { name: "E4", value: 0, price: 250 },
      { name: "E5", value: 0, price: 250 },
      { name: "E6", value: 0, price: 250 },
      { name: "E7", value: 1, price: 250 },
      { name: "E8", value: 0, price: 250 },
      { name: "E9", value: 0, price: 250 },
      { name: "E10", value: 0, price: 250 },
      { name: "E11", value: 0, price: 250 },
      { name: "E12", value: 0, price: 250 },
      { name: "E13", value: 0, price: 250 },
      { name: "E14", value: 0, price: 250 },
      { name: "E15", value: 0, price: 250 },
      { name: "E16", value: 0, price: 250 },
      { name: "E17", value: 0, price: 250 },
      { name: "E18", value: 0, price: 250 },
      { name: "E19", value: 0, price: 250 },
      { name: "E20", value: 0, price: 250 },
      { name: "E21", value: 0, price: 250 },
      { name: "E22", value: 0, price: 250 },
      { name: "E23", value: 0, price: 250 },
      { name: "E24", value: 0, price: 250 },
    ],
    F: [
      { name: "F1", value: 0, price: 250 },
      { name: "F2", value: 0, price: 250 },
      { name: "F3", value: 0, price: 250 },
      { name: "F4", value: 0, price: 250 },
      { name: "F5", value: 0, price: 250 },
      { name: "F6", value: 0, price: 250 },
      { name: "F7", value: 0, price: 250 },
      { name: "F8", value: 0, price: 250 },
      { name: "F9", value: 0, price: 250 },
      { name: "F10", value: 1, price: 250 },
      { name: "F11", value: 0, price: 250 },
      { name: "F12", value: 0, price: 250 },
      { name: "F13", value: 0, price: 250 },
      { name: "F14", value: 0, price: 250 },
      { name: "F15", value: 0, price: 250 },
      { name: "F16", value: 0, price: 250 },
      { name: "F17", value: 0, price: 250 },
      { name: "F18", value: 0, price: 250 },
      { name: "F19", value: 0, price: 250 },
      { name: "F20", value: 0, price: 250 },
    ],
    G: [
      { name: "G1", value: 0, price: 250 },
      { name: "G2", value: 0, price: 250 },
      { name: "G3", value: 0, price: 250 },
      { name: "G4", value: 0, price: 250 },
      { name: "G5", value: 0, price: 250 },
      { name: "G6", value: 0, price: 250 },
      { name: "G7", value: 0, price: 250 },
      { name: "G8", value: 0, price: 250 },
      { name: "G9", value: 0, price: 250 },
      { name: "G10", value: 0, price: 250 },
      { name: "G11", value: 0, price: 250 },
      { name: "G12", value: 0, price: 250 },
      { name: "G13", value: 0, price: 250 },
      { name: "G14", value: 0, price: 250 },
      { name: "G15", value: 0, price: 250 },
      { name: "G16", value: 0, price: 250 },
      { name: "G17", value: 0, price: 250 },
      { name: "G18", value: 0, price: 250 },
      { name: "G19", value: 0, price: 250 },
      { name: "G20", value: 0, price: 250 },
      { name: "G21", value: 0, price: 250 },
      { name: "G22", value: 0, price: 250 },
      { name: "G23", value: 0, price: 250 },
      { name: "G24", value: 0, price: 250 },
    ],
    H: [
      { name: "H1", value: 0, price: 250 },
      { name: "H2", value: 0, price: 250 },
      { name: "H3", value: 0, price: 250 },
      { name: "H4", value: 0, price: 250 },
      { name: "H5", value: 0, price: 250 },
      { name: "H6", value: 0, price: 250 },
      { name: "H7", value: 0, price: 250 },
      { name: "H8", value: 0, price: 250 },
      { name: "H9", value: 0, price: 250 },
      { name: "H10", value: 0, price: 250 },
      { name: "H11", value: 0, price: 250 },
      { name: "H12", value: 0, price: 250 },
      { name: "H13", value: 0, price: 250 },
      { name: "H14", value: 0, price: 250 },
      { name: "H15", value: 0, price: 250 },
      { name: "H16", value: 0, price: 250 },
      { name: "H17", value: 0, price: 250 },
      { name: "H18", value: 0, price: 250 },
      { name: "H19", value: 0, price: 250 },
      { name: "H20", value: 0, price: 250 },
      { name: "H21", value: 0, price: 250 },
      { name: "H22", value: 0, price: 250 },
      { name: "H23", value: 0, price: 250 },
      { name: "H24", value: 0, price: 250 },
    ],
    I: [
      { name: "I1", value: 0, price: 250 },
      { name: "I2", value: 0, price: 250 },
      { name: "I3", value: 0, price: 250 },
      { name: "I4", value: 0, price: 250 },
      { name: "I5", value: 0, price: 250 },
      { name: "I6", value: 0, price: 250 },
      { name: "I7", value: 0, price: 250 },
      { name: "I8", value: 0, price: 250 },
      { name: "I9", value: 0, price: 250 },
      { name: "I10", value: 0, price: 250 },
      { name: "I11", value: 0, price: 250 },
      { name: "I12", value: 0, price: 250 },
      { name: "I13", value: 0, price: 250 },
      { name: "I14", value: 0, price: 250 },
      { name: "I15", value: 0, price: 250 },
      { name: "I16", value: 0, price: 250 },
      { name: "I17", value: 0, price: 250 },
      { name: "I18", value: 0, price: 250 },
      { name: "I19", value: 0, price: 250 },
      { name: "I20", value: 0, price: 250 },
      { name: "I21", value: 0, price: 250 },
      { name: "I22", value: 0, price: 250 },
      { name: "I23", value: 0, price: 250 },
      { name: "I24", value: 0, price: 250 },
    ],
    J: [
      { name: "J1", value: 0, price: 250 },
      { name: "J2", value: 0, price: 250 },
      { name: "J3", value: 0, price: 250 },
      { name: "J4", value: 0, price: 250 },
      { name: "J5", value: 0, price: 250 },
      { name: "J6", value: 0, price: 250 },
      { name: "J7", value: 0, price: 250 },
      { name: "J8", value: 0, price: 250 },
      { name: "J9", value: 0, price: 250 },
      { name: "J10", value: 0, price: 250 },
      { name: "J11", value: 0, price: 250 },
      { name: "J12", value: 1, price: 250 },
      { name: "J13", value: 0, price: 250 },
      { name: "J14", value: 0, price: 250 },
      { name: "J15", value: 0, price: 250 },
      { name: "J16", value: 0, price: 250 },
      { name: "J17", value: 0, price: 250 },
      { name: "J18", value: 0, price: 250 },
      { name: "J19", value: 0, price: 250 },
      { name: "J20", value: 0, price: 250 },
      { name: "J21", value: 0, price: 250 },
      { name: "J22", value: 0, price: 250 },
      { name: "J23", value: 0, price: 250 },
      { name: "J24", value: 0, price: 250 },
    ],
    K: [
      { name: "K1", value: 0, price: 250 },
      { name: "K2", value: 0, price: 250 },
      { name: "K3", value: 0, price: 250 },
      { name: "K4", value: 0, price: 250 },
      { name: "K5", value: 0, price: 250 },
      { name: "K6", value: 0, price: 250 },
      { name: "K7", value: 0, price: 250 },
      { name: "K8", value: 0, price: 250 },
      { name: "K9", value: 0, price: 250 },
      { name: "K10", value: 0, price: 250 },
      { name: "K11", value: 0, price: 250 },
      { name: "K12", value: 0, price: 250 },
      { name: "K13", value: 0, price: 250 },
      { name: "K14", value: 0, price: 250 },
      { name: "K15", value: 0, price: 250 },
      { name: "K16", value: 0, price: 250 },
      { name: "K17", value: 0, price: 250 },
      { name: "K18", value: 0, price: 250 },
      { name: "K19", value: 0, price: 250 },
      { name: "K20", value: 0, price: 250 },
    ],
    L: [
      { name: "L1", value: 0 },
      { name: "L2", value: 0 },
      { name: "L3", value: 0 },
      { name: "L4", value: 0 },
      { name: "L5", value: 0 },
      { name: "L6", value: 0 },
      { name: "L7", value: 0 },
      { name: "L8", value: 0 },
      { name: "L9", value: 0 },
      { name: "L10", value: 0 },
      { name: "L11", value: 0 },
      { name: "L12", value: 0 },
      { name: "L13", value: 0 },
      { name: "L14", value: 0 },
      { name: "L15", value: 0 },
      { name: "L16", value: 0 },
      { name: "L17", value: 0 },
      { name: "L18", value: 0 },
      { name: "L19", value: 0 },
      { name: "L20", value: 0 },
    ],
    M: [
      { name: "M1", value: 0 },
      { name: "M2", value: 0 },
      { name: "M3", value: 0 },
      { name: "M4", value: 0 },
      { name: "M5", value: 0 },
      { name: "M6", value: 0 },
      { name: "M7", value: 0 },
      { name: "M8", value: 0 },
      { name: "M9", value: 0 },
      { name: "M10", value: 0 },
      { name: "M11", value: 0 },
      { name: "M12", value: 0 },
      { name: "M13", value: 0 },
      { name: "M14", value: 0 },
      { name: "M15", value: 0 },
      { name: "M16", value: 0 },
      { name: "M17", value: 0 },
      { name: "M18", value: 0 },
      { name: "M19", value: 0 },
      { name: "M20", value: 0 },
    ],
    N: [
      { name: "N1", value: 0 },
      { name: "N2", value: 0 },
      { name: "N3", value: 0 },
      { name: "N4", value: 0 },
      { name: "N5", value: 0 },
      { name: "N6", value: 0 },
      { name: "N7", value: 0 },
      { name: "N8", value: 0 },
      { name: "N9", value: 0 },
      { name: "N10", value: 0 },
      { name: "N11", value: 0 },
      { name: "N12", value: 0 },
      { name: "N13", value: 0 },
      { name: "N14", value: 0 },
      { name: "N15", value: 0 },
      { name: "N16", value: 0 },
      { name: "N17", value: 0 },
      { name: "N18", value: 0 },
      { name: "N19", value: 0 },
      { name: "N20", value: 0 },
    ],
    O: [
      { name: "O1", value: 0 },
      { name: "O2", value: 0 },
      { name: "O3", value: 0 },
      { name: "O4", value: 0 },
      { name: "O5", value: 0 },
      { name: "O6", value: 0 },
      { name: "O7", value: 0 },
      { name: "O8", value: 0 },
      { name: "O9", value: 0 },
      { name: "O10", value: 0 },
      { name: "O11", value: 0 },
      { name: "O12", value: 0 },
      { name: "O13", value: 0 },
      { name: "O14", value: 0 },
      { name: "O15", value: 0 },
      { name: "O16", value: 0 },
      { name: "O17", value: 0 },
      { name: "O18", value: 0 },
      { name: "O19", value: 0 },
      { name: "O20", value: 0 },
    ],
  },
  {
    time: "1:00 PM",
    A: [
      { name: "A1", value: 1, price: 420 },
      { name: "A2", value: 0, price: 420 },
      { name: "A3", value: 0, price: 420 },
      { name: "A4", value: 0, price: 420 },
      { name: "A5", value: 1, price: 420 },
      { name: "A6", value: 0, price: 420 },
      { name: "A7", value: 1, price: 420 },
      { name: "A8", value: 0, price: 420 },
      { name: "A9", value: 0, price: 420 },
      { name: "A10", value: 1, price: 420 },
      { name: "A11", value: 0, price: 420 },
      { name: "A12", value: 0, price: 420 },
      { name: "A13", value: 0, price: 420 },
      { name: "A14", value: 0, price: 420 },
      { name: "A15", value: 0, price: 420 },
    ],
    B: [
      { name: "B1", value: 0, price: 420 },
      { name: "B2", value: 0, price: 420 },
      { name: "B3", value: 0, price: 420 },
      { name: "B4", value: 0, price: 420 },
      { name: "B5", value: 1, price: 420 },
      { name: "B6", value: 0, price: 420 },
      { name: "B7", value: 0, price: 420 },
      { name: "B8", value: 1, price: 420 },
      { name: "B9", value: 0, price: 420 },
      { name: "B10", value: 0, price: 420 },
      { name: "B11", value: 1, price: 420 },
      { name: "B12", value: 0, price: 420 },
      { name: "B13", value: 0, price: 420 },
      { name: "B14", value: 0, price: 420 },
      { name: "B15", value: 0, price: 420 },
    ],
    C: [
      { name: "C1", value: 0, price: 250 },
      { name: "C2", value: 0, price: 250 },
      { name: "C3", value: 0, price: 250 },
      { name: "C4", value: 0, price: 250 },
      { name: "C5", value: 1, price: 250 },
      { name: "C6", value: 0, price: 250 },
      { name: "C7", value: 0, price: 250 },
      { name: "C8", value: 1, price: 250 },
      { name: "C9", value: 0, price: 250 },
      { name: "C10", value: 0, price: 250 },
      { name: "C11", value: 0, price: 250 },
      { name: "C12", value: 0, price: 250 },
      { name: "C13", value: 0, price: 250 },
      { name: "C14", value: 1, price: 250 },
      { name: "C15", value: 1, price: 250 },
      { name: "C16", value: 1, price: 250 },
      { name: "C17", value: 0, price: 250 },
      { name: "C18", value: 0, price: 250 },
      { name: "C19", value: 0, price: 250 },
      { name: "C20", value: 1, price: 250 },
      { name: "C21", value: 0, price: 250 },
      { name: "C22", value: 1, price: 250 },
      { name: "C23", value: 0, price: 250 },
      { name: "C24", value: 1, price: 250 },
    ],
    D: [
      { name: "D1", value: 0, price: 250 },
      { name: "D2", value: 0, price: 250 },
      { name: "D3", value: 0, price: 250 },
      { name: "D4", value: 1, price: 250 },
      { name: "D5", value: 1, price: 250 },
      { name: "D6", value: 1, price: 250 },
      { name: "D7", value: 1, price: 250 },
      { name: "D8", value: 0, price: 250 },
      { name: "D9", value: 1, price: 250 },
      { name: "D10", value: 1, price: 250 },
      { name: "D11", value: 1, price: 250 },
      { name: "D12", value: 0, price: 250 },
      { name: "D13", value: 0, price: 250 },
      { name: "D14", value: 0, price: 250 },
      { name: "D15", value: 0, price: 250 },
      { name: "D16", value: 0, price: 250 },
      { name: "D17", value: 0, price: 250 },
      { name: "D18", value: 0, price: 250 },
      { name: "D19", value: 0, price: 250 },
      { name: "D20", value: 0, price: 250 },
      { name: "D21", value: 0, price: 250 },
      { name: "D22", value: 0, price: 250 },
      { name: "D23", value: 1, price: 250 },
      { name: "D24", value: 1, price: 250 },
    ],
    E: [
      { name: "E1", value: 0, price: 250 },
      { name: "E2", value: 0, price: 250 },
      { name: "E3", value: 1, price: 250 },
      { name: "E4", value: 1, price: 250 },
      { name: "E5", value: 0, price: 250 },
      { name: "E6", value: 0, price: 250 },
      { name: "E7", value: 1, price: 250 },
      { name: "E8", value: 1, price: 250 },
      { name: "E9", value: 0, price: 250 },
      { name: "E10", value: 0, price: 250 },
      { name: "E11", value: 0, price: 250 },
      { name: "E12", value: 0, price: 250 },
      { name: "E13", value: 0, price: 250 },
      { name: "E14", value: 1, price: 250 },
      { name: "E15", value: 1, price: 250 },
      { name: "E16", value: 0, price: 250 },
      { name: "E17", value: 1, price: 250 },
      { name: "E18", value: 0, price: 250 },
      { name: "E19", value: 0, price: 250 },
      { name: "E20", value: 0, price: 250 },
      { name: "E21", value: 1, price: 250 },
      { name: "E22", value: 0, price: 250 },
      { name: "E23", value: 0, price: 250 },
      { name: "E24", value: 1, price: 250 },
    ],
    F: [
      { name: "F1", value: 0, price: 250 },
      { name: "F2", value: 1, price: 250 },
      { name: "F3", value: 1, price: 250 },
      { name: "F4", value: 0, price: 250 },
      { name: "F5", value: 1, price: 250 },
      { name: "F6", value: 0, price: 250 },
      { name: "F7", value: 1, price: 250 },
      { name: "F8", value: 1, price: 250 },
      { name: "F9", value: 0, price: 250 },
      { name: "F10", value: 1, price: 250 },
      { name: "F11", value: 0, price: 250 },
      { name: "F12", value: 0, price: 250 },
      { name: "F13", value: 0, price: 250 },
      { name: "F14", value: 0, price: 250 },
      { name: "F15", value: 0, price: 250 },
      { name: "F16", value: 1, price: 250 },
      { name: "F17", value: 0, price: 250 },
      { name: "F18", value: 0, price: 250 },
      { name: "F19", value: 1, price: 250 },
      { name: "F20", value: 0, price: 250 },
    ],
    G: [
      { name: "G1", value: 0, price: 250 },
      { name: "G2", value: 1, price: 250 },
      { name: "G3", value: 0, price: 250 },
      { name: "G4", value: 0, price: 250 },
      { name: "G5", value: 1, price: 250 },
      { name: "G6", value: 0, price: 250 },
      { name: "G7", value: 0, price: 250 },
      { name: "G8", value: 0, price: 250 },
      { name: "G9", value: 1, price: 250 },
      { name: "G10", value: 0, price: 250 },
      { name: "G11", value: 0, price: 250 },
      { name: "G12", value: 0, price: 250 },
      { name: "G13", value: 1, price: 250 },
      { name: "G14", value: 0, price: 250 },
      { name: "G15", value: 0, price: 250 },
      { name: "G16", value: 0, price: 250 },
      { name: "G17", value: 0, price: 250 },
      { name: "G18", value: 0, price: 250 },
      { name: "G19", value: 0, price: 250 },
      { name: "G20", value: 0, price: 250 },
      { name: "G21", value: 0, price: 250 },
      { name: "G22", value: 1, price: 250 },
      { name: "G23", value: 0, price: 250 },
      { name: "G24", value: 0, price: 250 },
    ],
    H: [
      { name: "H1", value: 0, price: 250 },
      { name: "H2", value: 0, price: 250 },
      { name: "H3", value: 1, price: 250 },
      { name: "H4", value: 0, price: 250 },
      { name: "H5", value: 0, price: 250 },
      { name: "H6", value: 1, price: 250 },
      { name: "H7", value: 0, price: 250 },
      { name: "H8", value: 1, price: 250 },
      { name: "H9", value: 1, price: 250 },
      { name: "H10", value: 0, price: 250 },
      { name: "H11", value: 0, price: 250 },
      { name: "H12", value: 0, price: 250 },
      { name: "H13", value: 0, price: 250 },
      { name: "H14", value: 0, price: 250 },
      { name: "H15", value: 0, price: 250 },
      { name: "H16", value: 0, price: 250 },
      { name: "H17", value: 0, price: 250 },
      { name: "H18", value: 0, price: 250 },
      { name: "H19", value: 0, price: 250 },
      { name: "H20", value: 0, price: 250 },
      { name: "H21", value: 0, price: 250 },
      { name: "H22", value: 0, price: 250 },
      { name: "H23", value: 1, price: 250 },
      { name: "H24", value: 1, price: 250 },
    ],
    I: [
      { name: "I1", value: 1, price: 250 },
      { name: "I2", value: 1, price: 250 },
      { name: "I3", value: 0, price: 250 },
      { name: "I4", value: 0, price: 250 },
      { name: "I5", value: 0, price: 250 },
      { name: "I6", value: 1, price: 250 },
      { name: "I7", value: 1, price: 250 },
      { name: "I8", value: 1, price: 250 },
      { name: "I9", value: 1, price: 250 },
      { name: "I10", value: 0, price: 250 },
      { name: "I11", value: 0, price: 250 },
      { name: "I12", value: 0, price: 250 },
      { name: "I13", value: 0, price: 250 },
      { name: "I14", value: 0, price: 250 },
      { name: "I15", value: 0, price: 250 },
      { name: "I16", value: 0, price: 250 },
      { name: "I17", value: 1, price: 250 },
      { name: "I18", value: 0, price: 250 },
      { name: "I19", value: 1, price: 250 },
      { name: "I20", value: 0, price: 250 },
      { name: "I21", value: 1, price: 250 },
      { name: "I22", value: 0, price: 250 },
      { name: "I23", value: 0, price: 250 },
      { name: "I24", value: 0, price: 250 },
    ],
    J: [
      { name: "J1", value: 0, price: 250 },
      { name: "J2", value: 0, price: 250 },
      { name: "J3", value: 0, price: 250 },
      { name: "J4", value: 0, price: 250 },
      { name: "J5", value: 1, price: 250 },
      { name: "J6", value: 0, price: 250 },
      { name: "J7", value: 1, price: 250 },
      { name: "J8", value: 0, price: 250 },
      { name: "J9", value: 0, price: 250 },
      { name: "J10", value: 1, price: 250 },
      { name: "J11", value: 0, price: 250 },
      { name: "J12", value: 1, price: 250 },
      { name: "J13", value: 0, price: 250 },
      { name: "J14", value: 0, price: 250 },
      { name: "J15", value: 0, price: 250 },
      { name: "J16", value: 0, price: 250 },
      { name: "J17", value: 0, price: 250 },
      { name: "J18", value: 0, price: 250 },
      { name: "J19", value: 0, price: 250 },
      { name: "J20", value: 0, price: 250 },
      { name: "J21", value: 0, price: 250 },
      { name: "J22", value: 0, price: 250 },
      { name: "J23", value: 0, price: 250 },
      { name: "J24", value: 0, price: 250 },
    ],
    K: [
      { name: "K1", value: 0, price: 250 },
      { name: "K2", value: 0, price: 250 },
      { name: "K3", value: 0, price: 250 },
      { name: "K4", value: 0, price: 250 },
      { name: "K5", value: 0, price: 250 },
      { name: "K6", value: 0, price: 250 },
      { name: "K7", value: 0, price: 250 },
      { name: "K8", value: 0, price: 250 },
      { name: "K9", value: 0, price: 250 },
      { name: "K10", value: 0, price: 250 },
      { name: "K11", value: 0, price: 250 },
      { name: "K12", value: 0, price: 250 },
      { name: "K13", value: 0, price: 250 },
      { name: "K14", value: 0, price: 250 },
      { name: "K15", value: 0, price: 250 },
      { name: "K16", value: 0, price: 250 },
      { name: "K17", value: 0, price: 250 },
      { name: "K18", value: 0, price: 250 },
      { name: "K19", value: 0, price: 250 },
      { name: "K20", value: 0, price: 250 },
    ],
    L: [
      { name: "L1", value: 0 },
      { name: "L2", value: 0 },
      { name: "L3", value: 0 },
      { name: "L4", value: 0 },
      { name: "L5", value: 0 },
      { name: "L6", value: 0 },
      { name: "L7", value: 0 },
      { name: "L8", value: 0 },
      { name: "L9", value: 0 },
      { name: "L10", value: 0 },
      { name: "L11", value: 0 },
      { name: "L12", value: 0 },
      { name: "L13", value: 0 },
      { name: "L14", value: 0 },
      { name: "L15", value: 0 },
      { name: "L16", value: 0 },
      { name: "L17", value: 0 },
      { name: "L18", value: 0 },
      { name: "L19", value: 0 },
      { name: "L20", value: 0 },
    ],
    M: [
      { name: "M1", value: 0 },
      { name: "M2", value: 0 },
      { name: "M3", value: 0 },
      { name: "M4", value: 0 },
      { name: "M5", value: 0 },
      { name: "M6", value: 0 },
      { name: "M7", value: 0 },
      { name: "M8", value: 0 },
      { name: "M9", value: 0 },
      { name: "M10", value: 0 },
      { name: "M11", value: 0 },
      { name: "M12", value: 0 },
      { name: "M13", value: 0 },
      { name: "M14", value: 0 },
      { name: "M15", value: 0 },
      { name: "M16", value: 0 },
      { name: "M17", value: 0 },
      { name: "M18", value: 0 },
      { name: "M19", value: 0 },
      { name: "M20", value: 0 },
    ],
    N: [
      { name: "N1", value: 0 },
      { name: "N2", value: 0 },
      { name: "N3", value: 0 },
      { name: "N4", value: 0 },
      { name: "N5", value: 0 },
      { name: "N6", value: 0 },
      { name: "N7", value: 0 },
      { name: "N8", value: 0 },
      { name: "N9", value: 0 },
      { name: "N10", value: 0 },
      { name: "N11", value: 0 },
      { name: "N12", value: 0 },
      { name: "N13", value: 0 },
      { name: "N14", value: 0 },
      { name: "N15", value: 0 },
      { name: "N16", value: 0 },
      { name: "N17", value: 0 },
      { name: "N18", value: 0 },
      { name: "N19", value: 0 },
      { name: "N20", value: 0 },
    ],
    O: [
      { name: "O1", value: 0 },
      { name: "O2", value: 0 },
      { name: "O3", value: 0 },
      { name: "O4", value: 0 },
      { name: "O5", value: 0 },
      { name: "O6", value: 0 },
      { name: "O7", value: 0 },
      { name: "O8", value: 0 },
      { name: "O9", value: 0 },
      { name: "O10", value: 0 },
      { name: "O11", value: 0 },
      { name: "O12", value: 0 },
      { name: "O13", value: 0 },
      { name: "O14", value: 0 },
      { name: "O15", value: 0 },
      { name: "O16", value: 0 },
      { name: "O17", value: 0 },
      { name: "O18", value: 0 },
      { name: "O19", value: 0 },
      { name: "O20", value: 0 },
    ],
  },
];
let orders = [];
let person = [
  { name: "Admin", email: "test@test.com", password: "test123", number: "" },
];
let movieData = [
  {
    Title: "Avatar",
    Year: "2009",
    Rated: "PG-13",
    Released: "18 Dec 2009",
    Runtime: "162 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "James Cameron",
    Writer: "James Cameron",
    Actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
    Plot: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    Language: "English,Spanish,Hindi",
    Country: "USA, UK",
    Awards: "Won 3 Oscars. Another 80 wins & 121 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
    Metascore: "83",
    imdbRating: "7.9",
    imdbVotes: "890,617",
    imdbID: "tt0499549",
    Type: "movie",
    Response: "True",
    Format: "2D,IMAX",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNzM2MDk3MTcyMV5BMl5BanBnXkFtZTcwNjg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    Title: "300",
    Year: "2006",
    Rated: "R",
    Released: "09 Mar 2007",
    Runtime: "117 min",
    Genre: "Action, Drama, Fantasy",
    Director: "Zack Snyder",
    Writer:
      "Zack Snyder (screenplay), Kurt Johnstad (screenplay), Michael Gordon (screenplay), Frank Miller (graphic novel), Lynn Varley (graphic novel)",
    Actors: "Gerard Butler, Lena Headey, Dominic West, David Wenham",
    Plot: "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
    Language: "English,Hindi,Telgu,Malyalam",
    Country: "USA",
    Awards: "16 wins & 42 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX300.jpg",
    Metascore: "52",
    imdbRating: "7.7",
    imdbVotes: "611,046",
    imdbID: "tt0416449",
    Type: "movie",
    Format: "3D,4DX",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNTg5MzMwMV5BMl5BanBnXkFtZTcwMzA2NTIyMw@@._V1_SX1777_CR0,0,1777,937_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwNTgyNTMzNF5BMl5BanBnXkFtZTcwNDA2NTIyMw@@._V1_SX1777_CR0,0,1777,935_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0MjQzOTEwMV5BMl5BanBnXkFtZTcwMzE2NTIyMw@@._V1_SX1777_CR0,0,1777,947_AL_.jpg",
    ],
  },
  {
    Title: "The Avengers",
    Year: "2012",
    Rated: "PG-13",
    Released: "04 May 2012",
    Runtime: "143 min",
    Genre: "Action, Sci-Fi, Thriller",
    Director: "Joss Whedon",
    Format: "2D,IMAX,3D",
    Writer: "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian,Punjabi",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg",
    Metascore: "69",
    imdbRating: "8.1",
    imdbVotes: "1,003,301",
    imdbID: "tt0848228",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0NjY0NzE4OTReQTJeQWpwZ15BbWU3MDczODg2Nzc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE1MzEzMjcyM15BMl5BanBnXkFtZTcwNDM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwMzM2MTg1M15BMl5BanBnXkFtZTcwNjM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4NzM2Mjc5MV5BMl5BanBnXkFtZTcwMTkwOTY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3MzQ3NjA5N15BMl5BanBnXkFtZTcwMzY5OTY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
    ],
  },
  {
    Title: "The Wolf of Wall Street",
    Year: "2013",
    Rated: "R",
    Released: "25 Dec 2013",
    Runtime: "180 min",
    Format: "IMAX",
    Genre: "Biography, Comedy, Crime",
    Director: "Martin Scorsese",
    Writer: "Terence Winter (screenplay), Jordan Belfort (book)",
    Actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
    Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    Language: "English, French",
    Country: "USA",
    Awards: "Nominated for 5 Oscars. Another 35 wins & 154 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    Metascore: "75",
    imdbRating: "8.2",
    imdbVotes: "786,985",
    imdbID: "tt0993846",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDIwMDIxNzk3Ml5BMl5BanBnXkFtZTgwMTg0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NzAxODAyMl5BMl5BanBnXkFtZTgwMDg0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTExMDk1MDE4NzVeQTJeQWpwZ15BbWU4MDM4NDM0ODAx._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg3MTY4NDk4Nl5BMl5BanBnXkFtZTgwNjc0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzMTg4MDI0Ml5BMl5BanBnXkFtZTgwOTY0MzQ4MDE@._V1_SY1000_CR0,0,1553,1000_AL_.jpg",
    ],
  },
  {
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Format: "2D,IMAX,3D",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Language: "English",
    Country: "USA, UK",
    Awards: "Won 1 Oscar. Another 39 wins & 134 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg",
    Metascore: "74",
    imdbRating: "8.6",
    imdbVotes: "937,412",
    imdbID: "tt0816692",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NTEwOTMxMV5BMl5BanBnXkFtZTgwMjMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzQ5ODE2MzEwM15BMl5BanBnXkFtZTgwMTMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg4Njk4MzY0Nl5BMl5BanBnXkFtZTgwMzIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzE3MTM0MTc3Ml5BMl5BanBnXkFtZTgwMDIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjYzNjE2NDk3N15BMl5BanBnXkFtZTgwNzEyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    Title: "Game of Thrones",
    Year: "2011–",
    Rated: "TV-MA",
    Released: "17 Apr 2011",
    Format: "2D,IMAX,3D",
    Runtime: "56 min",
    Genre: "Adventure, Drama, Fantasy",
    Director: "N/A",
    Writer: "David Benioff, D.B. Weiss",
    Actors: "Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
    Plot: "While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.",
    Language: "English,Hindi,Malyalam,Punjabi",
    Country: "USA, UK",
    Awards: "Won 1 Golden Globe. Another 185 wins & 334 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMjM5OTQ1MTY5Nl5BMl5BanBnXkFtZTgwMjM3NzMxODE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "1,046,830",
    imdbID: "tt0944947",
    Type: "series",
    totalSeasons: "7",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDc1MGUyNzItNWRkOC00MjM1LWJjNjMtZTZlYWIxMGRmYzVlXkEyXkFqcGdeQXVyMzU3MDEyNjk@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZjZkN2M5ODgtMjQ2OC00ZjAxLWE1MjMtZDE0OTNmNGM0NWEwXkEyXkFqcGdeQXVyNjUxNzgwNTE@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMDk4Y2Y1MDAtNGVmMC00ZTlhLTlmMmQtYjcyN2VkNzUzZjg2XkEyXkFqcGdeQXVyNjUxNzgwNTE@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjZjNWIzMzQtZWZjYy00ZTkwLWJiMTYtOWRkZDBhNWJhY2JmXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNTMyMTRjZWEtM2UxMS00ZjU5LWIxMTYtZDA5YmJhZmRjYTc4XkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
    ],
  },
  {
    Title: "Vikings",
    Year: "2013–",
    Rated: "TV-14",
    Format: "2D,IMAX,3D",
    Released: "03 Mar 2013",
    Runtime: "44 min",
    Genre: "Action, Drama, History",
    Director: "N/A",
    Writer: "Michael Hirst",
    Actors: "Travis Fimmel, Clive Standen, Gustaf Skarsgård, Katheryn Winnick",
    Plot: "The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.",
    Language: "English, Old English, Norse, Old, Latin",
    Country: "Ireland, Canada",
    Awards:
      "Nominated for 7 Primetime Emmys. Another 17 wins & 49 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BOTEzNzI3MDc0N15BMl5BanBnXkFtZTgwMzk1MzA5NzE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "198,041",
    imdbID: "tt2306299",
    Format: "2D,IMAX,3D",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM5MTM1ODUxNV5BMl5BanBnXkFtZTgwNTAzOTI2ODE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNzU2NDcxODMyOF5BMl5BanBnXkFtZTgwNDAzOTI2ODE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMzMzIzOTU2M15BMl5BanBnXkFtZTgwODMzMTkyODE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NTQ2MDA3NF5BMl5BanBnXkFtZTgwODkxMDUxODE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcxOTQ3NTA5N15BMl5BanBnXkFtZTgwMzExMDUxODE@._V1_SY1000_SX1500_AL_.jpg",
    ],
  },
  {
    Title: "Gotham",
    Year: "2014–",
    Rated: "TV-14",
    Released: "01 Aug 2014",
    Runtime: "42 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Format: "2D,IMAX,3D",
    Format: "2D,IMAX,3D",
    Writer: "Bruno Heller",
    Actors: "Ben McKenzie, Donal Logue, David Mazouz, Sean Pertwee",
    Plot: "The story behind Detective James Gordon's rise to prominence in Gotham City in the years before Batman's arrival.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 4 Primetime Emmys. Another 3 wins & 22 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTY2MjMwNDE4OV5BMl5BanBnXkFtZTgwNjI1NjU0OTE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "133,375",
    imdbID: "tt3749900",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
    Format: "2D,IMAX,3D",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDI3ODYyODY4OV5BMl5BanBnXkFtZTgwNjE5NDMwMDI@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5OTExMTIwNF5BMl5BanBnXkFtZTgwMjI5NDMwMDI@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA3MDY2NjA3MzBeQTJeQWpwZ15BbWU4MDU0MDkzODgx._V1_SX1499_CR0,0,1499,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3MzYzNDgzOV5BMl5BanBnXkFtZTgwMjQwOTM4ODE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQwODAyNjk0NF5BMl5BanBnXkFtZTgwODU4MzMyODE@._V1_SY1000_CR0,0,1500,1000_AL_.jpg",
    ],
  },
  {
    Title: "Power",
    Year: "2014–",
    Rated: "TV-MA",
    Released: "N/A",
    Runtime: "50 min",
    Genre: "Crime, Drama",
    Director: "N/A",
    Format: "2D,IMAX,3D",
    Writer: "Courtney Kemp Agboh",
    Actors: "Omari Hardwick, Joseph Sikora, Andy Bean, Lela Loren",
    Plot: 'James "Ghost" St. Patrick, a wealthy New York night club owner who has it all, catering for the city\'s elite and dreaming big, lives a double life as a drug kingpin.',
    Language: "English",
    Country: "USA",
    Awards: "1 win & 6 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BOTA4NTkzMjUzOF5BMl5BanBnXkFtZTgwNzg5ODkxOTE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "14,770",
    imdbID: "tt3281796",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2ODg0MzMzM15BMl5BanBnXkFtZTgwODYxODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcyMjA0MzczNV5BMl5BanBnXkFtZTgwNTIyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk0MTI0NzQ2NV5BMl5BanBnXkFtZTgwMDkxODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4Mzk1ODcxM15BMl5BanBnXkFtZTgwNDQyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwNTE0NDI1M15BMl5BanBnXkFtZTgwMDQyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
    ],
  },
  {
    Title: "Narcos",
    Year: "2015–",
    Format: "2D,IMAX,3D",
    Rated: "TV-MA",
    Released: "28 Aug 2015",
    Runtime: "49 min",
    Genre: "Biography, Crime, Drama",
    Director: "N/A",
    Writer: "Carlo Bernard, Chris Brancato, Doug Miro, Paul Eckstein",
    Actors: "Wagner Moura, Boyd Holbrook, Pedro Pascal, Joanna Christie",
    Plot: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Nominated for 2 Golden Globes. Another 4 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTU0ODQ4NDg2OF5BMl5BanBnXkFtZTgwNzczNTE4OTE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "8.9",
    imdbVotes: "118,680",
    imdbID: "tt2707408",
    Type: "series",
    totalSeasons: "2",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2MDMzMTc0MF5BMl5BanBnXkFtZTgwMTAyMzA1OTE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxMDkyOTEyNV5BMl5BanBnXkFtZTgwNjY3Mjc3OTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA2NDUwMTU2NV5BMl5BanBnXkFtZTgwNTI1Mzc3OTE@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BODA1NjAyMTQ3Ml5BMl5BanBnXkFtZTgwNjI1Mzc3OTE@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU0NzQ0OTAwNl5BMl5BanBnXkFtZTgwMDAyMzA1OTE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    Title: "Breaking Bad",
    Year: "2008–2013",
    Rated: "TV-14",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "N/A",
    Format: "2D,IMAX,3D",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
    Plot: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's financial future.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Won 2 Golden Globes. Another 132 wins & 218 nominations.",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "889,883",
    imdbID: "tt0903747",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgyMzI5NDc5Nl5BMl5BanBnXkFtZTgwMjM0MTI2MDE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NDkwNDk5NV5BMl5BanBnXkFtZTgwNDM0MTI2MDE@._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4NDcyNDMzMF5BMl5BanBnXkFtZTgwOTI0MTI2MDE@._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAzMTczMjM3NjFeQTJeQWpwZ15BbWU4MDc1MTI1MzAx._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5MTE3MTgwMF5BMl5BanBnXkFtZTgwOTQxMjUzMDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    ComingSoon: true,
    Title: "Doctor Strange",
    Year: "2016",
    Rated: "N/A",
    Released: "04 Nov 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Fantasy",
    Director: "Scott Derrickson",
    Format: "2D,IMAX,3D",
    Writer:
      "Scott Derrickson (screenplay), C. Robert Cargill (screenplay), Jon Spaihts (story by), Scott Derrickson (story by), C. Robert Cargill (story by), Steve Ditko (comic book)",
    Actors:
      "Rachel McAdams, Benedict Cumberbatch, Mads Mikkelsen, Tilda Swinton",
    Plot: "After his career is destroyed, a brilliant but arrogant and conceited surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "7.5",
    imdbVotes: "250,04",
    imdbID: "tt1211837",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3ODc1ODI5Ml5BMl5BanBnXkFtZTgwODMzMDY3OTE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxNTAyNTU0NV5BMl5BanBnXkFtZTgwNzMzMDY3OTE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NDc5NzUwNV5BMl5BanBnXkFtZTgwMDM3MDM2NzE@._V1_.jpg",
    ],
  },
  {
    ComingSoon: true,
    Title: "Rogue One: A Star Wars Story",
    Year: "2016",
    Format: "2D,IMAX,3D",
    Rated: "N/A",
    Released: "16 Dec 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Gareth Edwards",
    Writer:
      "Chris Weitz (screenplay), Tony Gilroy (screenplay), John Knoll (story), Gary Whitta (story), George Lucas (characters)",
    Actors: "Felicity Jones, Riz Ahmed, Mads Mikkelsen, Ben Mendelsohn",
    Plot: "The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.",
    Language: "English",
    Country: "USA",
    Awards: "1 nomination.",
    Poster:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQyMzI2OTA3OF5BMl5BanBnXkFtZTgwNDg5NjQ0OTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "181,00",
    imdbID: "tt3748528",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE3MzA4Nzk3NV5BMl5BanBnXkFtZTgwNjAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDMxMTQzMjQxM15BMl5BanBnXkFtZTgwNzAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyNjkxOTk5NV5BMl5BanBnXkFtZTgwODAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjM4MzExNDAyNl5BMl5BanBnXkFtZTgwOTAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE3NTgxMDcyNV5BMl5BanBnXkFtZTgwMDExMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
    ],
  },
  {
    ComingSoon: true,
    Title: "Assassin's Creed",
    Year: "2016",
    Rated: "N/A",
    Released: "21 Dec 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Fantasy",
    Format: "2D,IMAX,3D",
    Director: "Justin Kurzel",
    Writer:
      "Bill Collage (screenplay), Adam Cooper (screenplay), Michael Lesslie (screenplay)",
    Actors:
      "Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons",
    Plot: "When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.",
    Language: "English",
    Country: "UK, France, USA, Hong Kong",
    Awards: "N/A",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTU2MTQwMjU1OF5BMl5BanBnXkFtZTgwMDA5NjU5ODE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "5",
    imdbVotes: "15240",
    imdbID: "tt2094766",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BN2EyYzgyOWEtNTY2NS00NjRjLWJiNDYtMWViMjg5MWZjYjgzXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwOWYzOTctOTc4My00ZmJkLTgzMTctMmUxNDI5ODQzYzNjXkEyXkFqcGdeQXVyNDAyODU1Njc@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZTY5ZGUxMTAtYTU0OC00NGQ2LTkzNzgtZGZmNjlmNjY3MGU0XkEyXkFqcGdeQXVyNTY0MTkxMTg@._V1_SY1000_CR0,0,1500,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0MWYwZTEtYzc5Yi00NGM2LTg1YTctNjY2YzQ0NDJhZDAwXkEyXkFqcGdeQXVyNDAyODU1Njc@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
    ],
  },
  {
    ComingSoon: true,
    Format: "2D,IMAX,3D",
    Title: "Luke Cage",
    Year: "2016–",
    Rated: "TV-MA",
    Released: "30 Sep 2016",
    Runtime: "55 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Writer: "Cheo Hodari Coker",
    Actors: "Mahershala Ali, Mike Colter, Frankie Faison, Erik LaRay Harvey",
    Plot: "Given superstrength and durability by a sabotaged experiment, a wrongly accused man escapes prison to become a superhero for hire.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "7",
    imdbVotes: "5000",
    imdbID: "tt3322314",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMxNjc1NjI0NV5BMl5BanBnXkFtZTgwNzA0NzY0ODE@._V1_SY1000_CR0,0,1497,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1MDg3NjY2OF5BMl5BanBnXkFtZTgwNDE1NDU4OTE@._V1_SY1000_CR0,0,1497,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BOTYzOTQyNDYxNl5BMl5BanBnXkFtZTgwNzA1NDU4OTE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxMjA3MTQ5Ml5BMl5BanBnXkFtZTgwOTA1NDU4OTE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyNjg5ODYwNF5BMl5BanBnXkFtZTgwMTE1NDU4OTE@._V1_SY1000_CR0,0,1477,1000_AL_.jpg",
    ],
  },
];

let movies = movieData.map((m, index) => {
  return { ...m, id: index + 1 };
});
const port = process.env.PORT || 2410;
app.listen(port, () => console.log(`Listening on port ${port}!`));

app.get("/movies/:city", (req, res) => {
  let city = req.params.city;
  let { q, lang, format, genre } = req.query;
  let arr = movies;
  if (q)
    arr = arr.filter((f) => f.Title.toLowerCase().includes(q.toLowerCase()));
  if (lang) {
    let arr1 = lang.split(",");
    arr = arr.filter((f) => {
      const movieLanguages = f.Language.split(",");
      return arr1.some((l) => movieLanguages.includes(l));
    });
  }
  if (genre) {
    let arr1 = genre.split(",");
    arr = arr.filter((f) => {
      const movieGenre = f.Genre.split(",");
      return arr1.some((l) => movieGenre.includes(l));
    });
  }
  if (format) {
    let arr1 = format.split(",");
    arr = arr.filter((f) => {
      const movieFormat = f.Format.split(",");
      return arr1.some((l) => movieFormat.includes(l));
    });
  }

  res.send(arr);
});

app.get("/movies/:city/:id", (req, res) => {
  let movie = movies.find((f) => f.id === +req.params.id);
  if (movie) res.send(movie);
  else res.status(404).send("movie not found");
});

app.get("/movie/theater", (req, res) => {
  res.send(theater);
});

app.get("/movie/seates", (req, res) => {
  res.send(seats1);
});

app.post("/login", (req, res) => {
  let { email, password } = req.body;
  let per = person.find((f) => f.email === email && f.password === password);
  if (per) res.send(per);
  else res.status(401).send("not found");
});

app.post("/seat", (req, res) => {
  let body = req.body;
  orders.push(body);
  let updatedSeates = seats1;
  const seatsObj = updatedSeates.find((seat) => seat.time === body.time);
  if (!seatsObj) {
    res.send("seat not found");
  }
  for (const seat of body.tickets) {
    const prefix = seat.charAt(0);
    const seatArray = seatsObj[prefix];

    if (seatArray) {
      const seatToUpdate = seatArray.find((s) => s.name === seat);
      if (seatToUpdate) {
        seatToUpdate.value = 1;
      } else {
        console.log(
          `Seat ${seat} not found for time ${time} in the '${prefix}' array.`
        );
      }
    } else {
      console.log(`Seat ${seat} not found for time ${time}.`);
    }
  }
  seats1 = updatedSeates;
  res.send(body);
});

app.get("/orders", (req, res) => {
  res.send(orders);
});
app.post("/edit", (req, res) => {
  const { email } = req.body;
  const index = person.findIndex((f) => f.email === email);

  if (index >= 0) {
    person[index] = { ...person[index], ...req.body };
    res.send(person[index]);
  } else {
    res.status(400).send("Not found");
  }
});
